<?php

define('AT_CLASS', 'Drupal\at\AT');
define('AT_ROOT', __DIR__);

require_once __DIR__ . '/includes/at.api.php';
require_once __DIR__ . '/includes/at.hooks.php';

/**
 * Wrapper to helper classes.
 * @return \Drupal\at\AT
 */
function at($class_name = 'Drupal\at\AT')
{
    if (!$obj = &drupal_static(__FUNCTION__)) {
        $obj = new $class_name;
    }
    return $obj;
}

/**
 * Load route type by name.
 * @param string $name
 * @return \Drupal\at\Entity\RouteType
 */
function at_route_type_load($name)
{
    $types = entity_load_multiple_by_name('at_route_type', [$name]);
    return isset($types[$name]) ? $types[$name] : null;
}

/**
 * Load route by name.
 * @param string $name
 * @return \Drupal\at\Entity\Route
 */
function at_route_load($name)
{
    $routes = entity_load_multiple_by_name('at_route', [$name]);
    return isset($routes[$name]) ? $routes[$name] : null;
}
