<?php

define('AT_CLASS', 'Drupal\at\AT');
define('AT_ROOT', __DIR__);

require_once __DIR__ . '/includes/at.api.php';
require_once __DIR__ . '/includes/at.hooks.php';

/**
 * Wrapper to helper classes.
 *
 * @return \Drupal\at\AT
 */
function at($class_name = 'Drupal\at\AT')
{
    if (!$obj = &drupal_static(__FUNCTION__)) {
        $obj = new $class_name;
    }
    return $obj;
}

/**
 * Update service container
 */
function at_update_service_container() {
    drupal_static_reset();
    $at_container_file = variable_get('file_private_path', '') . '/at.container.php';
    if (file_exists($at_container_file)) {
        drupal_unlink($at_container_file);
    }
}

/**
 * Implements hook_flush_caches().
 */
function at_flush_caches()
{
    at_update_service_container();
}

/**
 * Implements hook_modules_enabled().
 */
function at_modules_enabled()
{
    at_update_service_container();
}

/**
 * Implements hook_modules_disabled().
 */
function at_modules_disabled()
{
    at_update_service_container();
}